micronaut:
  environments:
    active: local

# DynamoDB Configuration for SAM Local
aws:
  region: us-east-1
   
dynamodb:
  endpoint: http://host.docker.internal:8000
  table-name: user-test    
  region: us-east-1

s3:
  access-key: test
  secret-key: test
  expiration: 5
  region: us-east-1
  bucket-name: media-test
  endpoint: http://host.docker.internal:8000

quota:
  max-saved-sections: 10
  max-portfolios: 3

  
logger:
  levels:
    com.porflyo: DEBUG
    io.micronaut.http: DEBUG
    root: INFO
